global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-documenter-server"
    static_configs:
      - targets: ["host.docker.internal:9464"] # OTEL metrics exporter
      # If you're using Linux, replace host.docker.internal with your actual IP or container name.
